# Generated by Django 6.0.8 on 2026-09-02 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('SF', 'Square Foot'), ('LF', 'Linear Foot'), ('EA', 'Each'), ('CY', 'Cubic Yard'), ('SY', 'Square Yard'), ('HR', 'Hour')], max_length=8)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('keywords', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('csv', 'CSV')], default='csv', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='geometry_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ocr_engine',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ocr_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ocr_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('empty', 'Empty'), ('failed', 'Failed')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='EstimateRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('summary', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='CAD', max_length=8)),
                ('waste_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('markup_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('waste_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('markup_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_runs', to='drawings.drawing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=8)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('needs_review', models.BooleanField(default=False)),
                ('match_method', models.CharField(choices=[('exact', 'Exact'), ('keyword', 'Keyword'), ('unmatched', 'Unmatched')], max_length=16)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_line_items', to='drawings.annotation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='drawings.estimaterun')),
                ('unit_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='drawings.unitprice')),
            ],
            options={
                'ordering': ['page_number', 'category', 'description'],
            },
        ),
    ]
