# Generated by Django 6.0.8 on 2026-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_unitprice_annotation_geometry_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='match_confidence',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='match_method',
            field=models.CharField(choices=[('exact', 'Exact'), ('keyword', 'Keyword'), ('weak', 'Weak'), ('unmatched', 'Unmatched')], max_length=16),
        ),
    ]
